@echo off
cd /d "%~dp0"
echo Starting Flask backend...
start cmd /k "python app.py"
echo Waiting for Flask to start...
timeout /t 5 >nul
echo Opening app in browser...
start "" "http://localhost:5000"
